### PR TITLE
Memory going wild

### PR DESCRIPTION
**Pull request by argami**
Small change, because when a user was connecting but wasn't reciving messages memory start to grow  because the user channel was blocking and generating blocked goroutines going wild free

### CODE REVIEW

**Comment by argami** [comment]
Ups forgot to comment a small change to get member count with out affect the behaviour with the mutex

**Comment by argami** [comment]
Yes i totally forgot to change the test. 

The way its working now those tests aren't the best ones. Thats because in the moment of a member join could be after other memeber have send 20 messages and this new member shouldn't get those old messages. Any new member should start receiving messages in the moment we start to receive.

In the case you need to get old messages should implement buffered channels.

**Comment by grafov** [comment]
I reviewed the code and agree with the way you proposed. I'll merge the pull request as is. Tests will be adapted later.

**Comment by argami** [comment]
Awesome!

**Pull request merged**
