### PR TITLE
Enforces order of transmitted messages

### LINKED ISSUE #8: tests fail on Go 1.5.1
Hey there, I was looking into your bcast library and noticed some tests fail on my machine with Go 1.5.1:

```
dq@empit:bcast$ go test -v
=== RUN   TestNewGroupAndJoin
--- PASS: TestNewGroupAndJoin (0.00s)
=== RUN   TestUnjoin
--- PASS: TestUnjoin (0.00s)
=== RUN   TestBroadcast
--- FAIL: TestBroadcast (0.10s)
    bcast_test.go:85: not all messages broadcasted
=== RUN   TestBroadcastFromMember
--- FAIL: TestBroadcastFromMember (0.10s)
    bcast_test.go:114: not all messages broadcasted
=== RUN   TestGroupBroadcast
--- FAIL: TestGroupBroadcast (0.15s)
    bcast_test.go:141: not all messages broadcasted
=== RUN   TestBroadcastOnLargeNumberOfMembers
--- FAIL: TestBroadcastOnLargeNumberOfMembers (1.05s)
    bcast_test.go:168: not all messages broadcasted (11267/16256)
FAIL
exit status 1
FAIL    github.com/grafov/bcast 1.415s
dq@empit:bcast$ go version
go version go1.5.1 linux/amd64
```

cheers/

### PR DESCRIPTION
**Pull request by IvanMalison**
This involved an absolutely massive refactor that completely changed the
interface. Things should be much more robust now.

Fixes #8 and #9

### CODE REVIEW

**Comment by grafov** [comment]
@IvanMalison thank you for this contribution! I'll check it when I'll have some spare time.

**Comment by IvanMalison** [comment]
A better solution to the problem that this is trying to solve might be to use channel buffering.

The question then is what to do when a receiver channel buffer is full

**Comment by dvdplm** [comment]
@grafov Any chance we can get this merged?

**Comment by dpc** [comment]
I just hit that. I can confirm it's happening. Either this should be fixed, or documentation need to be very clear about this fact.

**Comment by IvanMalison** [comment]
this should be merged.

**Comment by grafov** [comment]
I agree with you but I forget about this project :( Sure, as it has stars and people try use it, let fix it.

**Comment by grafov** [comment]
@IvanMalison many thanks for making this code usable! :)

**Pull request merged**
